plone/app/discussion/catalog.py, plone/app/discussion/conversation.py
Fixes PR #58 that was mostly a proof of concept and room for discussion.
@tisto does this look better?
(sorry for PR #60, seems that github does not allow you to change the branch you base your pull request once you create it...)
=> Acquisition total comments

plone/app/discussion/testing.py, plone/app/discussion/tests/functional_test_comments.txt, plone/app/discussion/tests/test_catalog.py, plone/app/discussion/tests/test_comment.py, plone/app/discussion/tests/test_comments_viewlet.py, plone/app/discussion/tests/test_contentrules.py, plone/app/discussion/tests/test_conversation.py, plone/app/discussion/tests/test_events.py, plone/app/discussion/tests/test_indexers.py, plone/app/discussion/tests/test_moderation_view.py, plone/app/discussion/tests/test_notifications.py, plone/app/discussion/tests/test_workflow.py
This makes the tests for this package run about 20% faster on my computer (1:10 instead of 1:27)
=> create doc1 once in the text fixture rather than in setup for each test

.gitignore, CHANGES.rst, plone/app/discussion/i18n/plone-es.po, plone/app/discussion/locales/es/LC_MESSAGES/plone.app.discussion.po
Updated Spanish translation with check spell
=> Updated Spanish translation

CHANGES.rst, plone/app/discussion/browser/controlpanel.pt, plone/app/discussion/tests/functional_test_comments.txt
(fixes plone/Products.CMFPlone#1255)
=> Update Site Setup link in all control panels

CHANGES.rst, plone/app/discussion/tests/collection-integration-test.txt
Should be merged together with pull requests in other packages.
Central issue: https://github.com/plone/Products.CMFPlone/issues/1040
=> In tests, use ``selection.any`` in querystrings.

plone/app/discussion/i18n/plone-ru.po
fixed translate translation plone-ru.po
=> fixed translate translation plone-ru.po

CHANGES.rst, plone/app/discussion/browser/comments.pt
Fixes:
https://github.com/plone/plone.app.discussion/issues/90
=> Mark edit link for translation

CHANGES.rst, plone/app/discussion/profiles/default/workflows/comment_one_state_workflow/definition.xml
https://github.com/plone/Products.CMFPlone/issues/1975
=> Kakshay clean

CHANGES.rst, plone/app/discussion/tests/test_catalog.py, plone/app/discussion/tests/test_comment.py, plone/app/discussion/tests/test_comments_viewlet.py, plone/app/discussion/tests/test_contentrules.py, plone/app/discussion/tests/test_controlpanel.py, plone/app/discussion/tests/test_conversation.py, plone/app/discussion/tests/test_events.py, plone/app/discussion/tests/test_functional.py, plone/app/discussion/tests/test_indexers.py, plone/app/discussion/tests/test_notifications.py, plone/app/discussion/tests/test_workflow.py
see https://github.com/plone/Products.CMFPlone/issues/1882
=> kakshay unittest

CHANGES.rst, plone/app/discussion/interfaces.py, plone/app/discussion/tests/functional_test_comments.txt
Optional email field for anonymous.
=> Email validation

CHANGES.rst, docs/source/conf.py, plone/app/discussion/browser/comment.py, plone/app/discussion/browser/comments.py, plone/app/discussion/comment.py, plone/app/discussion/conversation.py, plone/app/discussion/tests/functional_test_comment_review_workflow.txt, plone/app/discussion/tests/functional_test_comments.txt, plone/app/discussion/tests/test_conversation.py, plone/app/discussion/tests/test_indexers.py
see https://github.com/plone/Products.CMFPlone/issues/2092
=> fix tests for plone.login merge

CHANGES.rst, plone/app/discussion/browser/controlpanel.py, plone/app/discussion/subscribers.zcml
see https://github.com/plone/Products.CMFPlone/issues/291
=> get rid of plone.app.controlpanel dependencies

news/168.bugfix, plone/app/discussion/tests/functional_test_comments.txt
... deprecate Plone 4 and older.
=> Fix test for Plone > 5

news/3178.bugfix, plone/app/discussion/tests/test_notifications.py
Part of https://github.com/plone/Products.CMFPlone/issues/3178.
Needs to be tested together with other PRs.
=> Fix tests with Products.MailHost 4.10.

news/174.bugfix, plone/app/discussion/tests/test_notifications.py
Fixes https://github.com/plone/plone.app.discussion/issues/174
=> Fix tests with Products.MailHost 4.11.

news/183.feature, plone/app/discussion/comment.py, plone/app/discussion/events.py, plone/app/discussion/interfaces.py, plone/app/discussion/subscribers.zcml, plone/app/discussion/tests/test_events.py
Implemented events:
- Comment modification: plone.app.discussion.interfaces.ICommentModifiedEvent
- Reply modification: plone.app.discussion.interfaces.IReplyModifiedEvent
=> Events for Comment and Reply modification

news/186.bugfix, setup.py
=> Remove cyclic dependency with Products.CMFPlone.

news/180.feature, plone/app/discussion/browser/configure.zcml, plone/app/discussion/permissions.zcml, plone/app/discussion/profiles/default/metadata.xml, plone/app/discussion/profiles/default/rolemap.xml, plone/app/discussion/upgrades.zcml
=> #180 Added 'View comments' permission

news/188.bugfix, plone/app/discussion/browser/moderation.py
That should not be done in Plone core.
Fixes issue #188.
=> Replaced use of plone.api.

news/3188.bugfix, setup.py
I will make a similar PR for several packages and will test them together.
=> Removed z3c.autoinclude.plugin entrypoint.

news/203.bugfix, plone/app/discussion/testing.py, plone/app/discussion/tests/functional_test_comment_review_workflow.txt, plone/app/discussion/tests/functional_test_comments.txt, plone/app/discussion/tests/test_comments_viewlet.py, plone/app/discussion/tests/test_workflow.py
To be merged before https://github.com/plone/Products.PlonePAS/pull/69
=> Use longer passwords for tests

news/3623.bugfix, plone/app/discussion/browser/comments.py
Fixes https://github.com/plone/Products.CMFPlone/issues/3623
=> Do not autofocus on the comments form.

news/+ignore.bugfix, plone/app/discussion/upgrades.py
While testing an upgrade from 5.2.x to 6.0.x I noticed that it first does a large upgrade step about the `image_scale` new catalog column, but then there's a laaaaaaarge gap of the server doing something without reporting anything at all 😱 is it dead? is still running? what is it doing?!
Adding these few lines of code solves the mystery 🎉
=> Report progress

news/265.bugfix, plone/app/discussion/browser/comments.pt, plone/app/discussion/browser/comments.py, plone/app/discussion/browser/moderation.pt, plone/app/discussion/browser/moderation.py, plone/app/discussion/browser/utils.py, plone/app/discussion/tests/test_comments_viewlet.py, plone/app/discussion/tests/test_moderation_view.py
=> Prevent impersonation for anonymous comments
