plone/plone.app.discussion

CHANGES.rst
docs/source/howtos/howto_extend_the_comment_form.txt
plone/app/discussion/__init__.py
plone/app/discussion/browser/captcha.zcml
plone/app/discussion/browser/comment.py
plone/app/discussion/browser/comments.pt
plone/app/discussion/browser/comments.py
plone/app/discussion/browser/configure.zcml
plone/app/discussion/browser/moderation.pt
plone/app/discussion/comment.py
plone/app/discussion/configure.zcml
plone/app/discussion/contentrules.py
plone/app/discussion/interfaces.py
plone/app/discussion/locales/update.sh
plone/app/discussion/notifications.zcml
plone/app/discussion/permissions.zcml
plone/app/discussion/subscribers.zcml

plone.app.discussion is an official Plone core package,
thus their translations belong to plone.app.locales.
This commit removes the plone.app.discussion domain and changes it for
plone.
This fixes:
https://github.com/plone/plone.app.discussion/issues/66
@vincentfretin what would be the best way to move the translations on the locales folder over to plone.app.locales? Do you have any handy tooling for that?

Use plone i18n domain

---

CHANGES.rst
plone/app/discussion/browser/controlpanel.pt
plone/app/discussion/browser/controlpanel.py

For the discussion controlpanel, change base URLs from portal URL to what getSite returns, but don't change the controlpanels context binding.
This allows for more flexibility when configuring it to be allowed on a sub site with a local registry.

Use ``getSite()`` instead of portal url

---

CHANGES.rst
plone/app/discussion/tests/test_comment.py

... by keeping the compatibility to the current (5.0.x and before) implementation of safe html

Make tests work with lxml safe html cleaner

---

CHANGES.rst
plone/app/discussion/browser/comments.py
plone/app/discussion/tests/functional_test_comments.txt

@maartenkling already saw this error and made pull request #56 with a failing test to show the problem.
My new pull request includes this test and fixes the problem.
The test does more, which is good, but the following already is enough to show the problem:
- Allow anonymous commenting and require email.
- As anonymous view a page where comments can be added. Don't even try to comment yet.
- No longer require email.
- As anonymous view the page again. The email field is not shown. Add a comment. There is a validation error saying required input is missing, but the field is not visible.
- Restart the instance and all is well again.
Or even easier:
- Allow anonymous commenting and require email.
- As anonymous view a page where comments can be added. Don't even try to comment yet.
- As …

Reset the required setting of the author_email widget each time.

---

CHANGES.rst
plone/app/discussion/browser/comments.pt
plone/app/discussion/browser/comments.py
plone/app/discussion/browser/conversation.py
plone/app/discussion/browser/javascripts/comments.js
plone/app/discussion/contentrules.py
plone/app/discussion/profiles/default/registry.xml
plone/app/discussion/profiles/default/rolemap.xml

Flake8 failures before:
```
plone/app/discussion/contentrules.py:20:5: E731 do not assign a lambda expression, use a def
plone/app/discussion/browser/comments.py:146:1: C901 'CommentForm.handleComment' is too complex (17)
plone/app/discussion/browser/conversation.py:29:1: C901 'ConversationView._enabled_for_archetypes' is too complex (14)
plone/app/discussion/browser/conversation.py:135:12: P002 found "hasattr", consider replacing it
plone/app/discussion/browser/migration.py:34:1: C901 'View.__call__' is too complex (32)
```
This pull request solves all of them, except the last one. But `migration.py` should be removed because it only works when Products.CMFDefault is there. I will make a separate pull request.
BTW, on my Mac I see a few isort errors due to comparing datetime and DateTime …

Flake8 cleanup

---

CHANGES.rst
setup.py

They are not only not needed, but they would prevent the migration to Python 3.
Thanks to @datakurre for the pointers.

Remove plone.app.robotframework extras

---

CHANGES.rst
plone/app/discussion/tests/functional_test_comments.txt

The related change was reverted in plone.app.contenttypes 1.4.15.
Test this in combination with plone/plone.app.contenttypes#496

Reverted test fix for richtext behavior.

---

CHANGES.rst
plone/app/discussion/browser/javascripts/moderation.js

Hi,
I've changed the method that wait the page is loaded in moderation.js file becouse $(window).load doesn't work in some version of FF and IE. $(document).ready seems to work properly.

window load on moderation.js doesn't work on some version of FF and IE

---

CHANGES.rst
plone/app/discussion/browser/controlpanel.pt
plone/app/discussion/browser/moderation.pt

Screen readers could now see and read correctly alerts/status messages.

[a11y] Added role attribute for portalMessage

---

CHANGES.rst
plone/app/discussion/tests/test_catalog.py

In order to get rid of the meta_type in the catalog this test change is needed.

Do not depend on the meta_type metadata in the catalog

---

news/77.feature
plone/app/discussion/subscribers.py

As https://github.com/collective/collective.solr/pull/102 finally got merged, it is time to use that on plone.app.discussion.
This minimal pull request is what is needed so that collective.solr (or other indexing tools) need to index comments on Solr.
Fixes (by ignoring) #77

Index comments on Solr

---

docs/source/howtos/howto_override_comments_viewlet.txt
news/157.bugfix
plone/app/discussion/browser/configure.zcml
plone/app/discussion/browser/controlpanel.pt
plone/app/discussion/browser/moderation.pt
plone/app/discussion/profiles/default/jsregistry.xml
plone/app/discussion/profiles/default/metadata.xml
plone/app/discussion/profiles/default/registry.xml
plone/app/discussion/upgrades.py
plone/app/discussion/upgrades.zcml

Same as in p.a.event. Fixes #157 
This still yields because `queryUtility(IResourceDirectory, name='persistent')` cannot find a resource directory:
```
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 337, in publish_module
Module ZPublisher.WSGIPublisher, line 255, in publish
Module ZPublisher.mapply, line 85, in mapply
Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
Module Products.CMFPlone.browser.admin, line 273, in __call__
Module Products.CMFPlone.factory, line 150, in addPloneSite
Module Products.GenericSetup.tool, line 393, in runAllImportStepsFromProfile
- __traceback_info__: profile-Products.CMFPlone:plone
Module Products.GenericSetup.tool, line 1474, in …
```

Register old js in legacy bundle to fix missing js

---

news/2952.bugfix
plone/app/discussion/configure.zcml

This is for our use of the `plone:static` directive.
See https://github.com/plone/Products.CMFPlone/issues/2952

Load zcml of plone.resource.

---

news/155.bugfix
plone/app/discussion/tests/robot/test_discussion.robot

I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.
Also re-enabled two previously disabled Robot tests.
In tandem with https://github.com/plone/plone.app.robotframework/pull/110
Closes https://github.com/plone/plone.app.discussion/issues/155

Default to a 4K x 4K browser window in Robot tests

---

news/163.enhancement
plone/app/discussion/browser/moderation.py
plone/app/discussion/comment.py
plone/app/discussion/tests/test_notifications.py

see https://github.com/plone/plone.app.discussion/issues/162

notification moderator: link to commented page to moderate comments instead of links to approve or delete with CSRF confirmation

---

CHANGES.rst
plone/app/discussion/browser/comments.pt
plone/app/discussion/browser/comments.py
plone/app/discussion/browser/controlpanel.pt
plone/app/discussion/browser/javascripts/moderation.js
plone/app/discussion/browser/moderation.pt
plone/app/discussion/profiles/default/controlpanel.xml
setup.py

Following the guidelines in plone/Products.CMFPlone#2967 and https://github.com/plone/plone.app.discussion/issues/169 I've updated the following templates from plone.app.discussion:
- plone.app.discussion.browser.controlpanel.pt
- plone.app.discussion.browser.comments.pt
- plone.app.discussion.browser.moderation.pt
Changes:
- Transform inputs into buttons
- Use btn-danger for form.button.DeleteComment
- Use 'btn-primary' for form.button.EditComment, Reply
- Add comments inside of a card
- Each card is a card-body
- Moderation buttons use 'btn-primary'
- documentByLine in the card-header
- commentBody in the card-body
- Add Bootstrap default 'form-group' to all forms

Update markup of templates to Bootstrap 5

---

news/199.bugfix
plone/app/discussion/profiles/default/metadata.xml
plone/app/discussion/profiles/default/workflows/comment_review_workflow/definition.xml
plone/app/discussion/upgrades.zcml

They were missing permissions on pending comments.
Fixes https://github.com/plone/plone.app.discussion/issues/199
Same as PR #200, but now for Plone 5.2.

Grant Site Administrators same workflow permissions as Managers [5.2]

---

news/199.bugfix
plone/app/discussion/profiles/default/metadata.xml
plone/app/discussion/profiles/default/workflows/comment_review_workflow/definition.xml
plone/app/discussion/upgrades.zcml

They were missing permissions on pending comments.
Fixes issue #199.
This is for master, Plone 6. I will do this on 5.2 as well, so I made some room for newer metadata versions there.

Grant Site Administrators same workflow permissions as Managers [master]

---

news/49.bugfix
plone/app/discussion/tests/test_comment.py

Needed to not fail with newer `plone.outputfilters` from this PR: https://github.com/plone/plone.outputfilters/pull/49
The tests then pass for both `plone.outputfilters` master and the PR branch.
Comments go through the outputfilters, and the PR branch calls `soup.prettify()` from `Beautifulsoup`, leading to more white space.
Sample test failures on Jenkins, see https://jenkins.plone.org/job/plip-plip-image-srcsets-3.8/5/#showFailuresLink
```
'<p>\n Go to http://www.plone.org\n</p>' != '<p>Go to http://www.plone.org</p>'
- <p>
-  Go to http://www.plone.org
? ^                          ^
+ <p>Go to http://www.plone.org</p>? ^^^                          ^^^^
- </p>
File "/srv/python3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
yield
File …
```

Test-only fix: normalize white space when comparing output of getText

---

news/227.internal
plone/app/discussion/tests/robot/test_moderation.robot

Fix test robot. Wait for the option is enable before select it.
Even after #226, we still had failure. This is a new attempt to make the test more robust.

Fix test "Add a Comment to a Document and bulk delete it"

---

news/235.internal
plone/app/discussion/tests/robot/test_moderation.robot

Capture the screen before the form is submitted, to debugging. Even after further attempts to fix the `Add a Comment to a Document and bulk delete it` test, it is still failing. See:
https://jenkins.plone.org/job/pull-request-6.0-3.11/1128/robot/report/robot_log.html#s1-s34-t1
So I took a screenshot before the form was sent, to see what's happening. The idea is to monitor Jenkins until an error occurs. Then we must remove the capture.

Capture screen to debug

---

news/237.internal
plone/app/discussion/browser/moderation.pt
plone/app/discussion/browser/moderation.py
plone/app/discussion/tests/robot/test_moderation.robot

The screenshot shows that the comment check was not selected before the form was submitted. Then we wait for the checkbox to be selected before submitting the form.
This fix: https://jenkins.plone.org/job/pull-request-6.1-3.10/21/robot/report/robot_log.html#s1-s34-t1

Fix robot test "Add a Comment to a Document and bulk delete it"

---

news/238.internal
plone/app/discussion/tests/robot/test_moderation.robot

The screenshot shows that the "Select all" checkbox is checked, but the other checkboxes are not. It may be that the test clicked on "Select all" before the event that selects all was attached to the checkbox. Then we wait for the event to be attached before clicking.
This fixes: https://jenkins.plone.org/job/pull-request-6.1-3.12/281/robot/report/robot_log.html#s1-s34-t1

Fix robot test `Add a Comment to a Document and bulk delete it`

---

news/239.internal
plone/app/discussion/tests/robot/test_moderation.robot

Prevents javascript error if undefined is returned.
This fixes: https://jenkins.plone.org/job/pull-request-6.0-3.11/1166/robot/report/robot_log.html#s1-s34-t1

Fix robot test `Add a Comment to a Document and bulk delete it` 3

---

plone/app/discussion/configure.zcml

Is that actually needed in Plone 6? 🤔

Drop five:registerPackage

---

news/+ignore.bugfix
news/222.bugfix
plone/app/discussion/configure.zcml
plone/app/discussion/profiles/default/metadata.xml
plone/app/discussion/profiles/default/types/Discussion_Item.xml
plone/app/discussion/profiles/to_2002/registry.xml
plone/app/discussion/profiles/to_2002/types/Discussion_Item.xml
plone/app/discussion/setuphandlers.py
plone/app/discussion/upgrades.zcml

I'm testing the upgrade to Plone 6 and noticed that on the toolbar when editing a comment the `view` action was missing an icon.
This fixes it.
That would require an upgrade step, should I add it here or on `plone.app.upgrade`? 🤔

Add missing icon

---

news/211.breaking
plone/app/discussion/interfaces.py
plone/app/discussion/testing.py
plone/app/discussion/tests/collection-integration-test.txt
plone/app/discussion/tests/test_controlpanel.py

This is an afterthought of the just merged [PLIP 3958](https://github.com/plone/Products.CMFPlone/issues/3958).
In 6.1 you have to explicitly install the add-on in the Add-ons control panel.
If you do that, then you obviously want discussions to be enabled globally.
I think this also helps for the Volto case, where a Discussion control panel is missing, so in Plone 6.0 you cannot even properly enable comments.
Also, this gets rid of some test code that was only needed for ancient ATTopics.  This is totally unrelated, I just happened to notice this while editing `testing.py`.

Globally enable comments on install

---

news/3813.feature
plone/app/discussion/tests/robot/keywords.robot
plone/app/discussion/tests/robot/test_allow_discussion.robot
plone/app/discussion/tests/robot/test_discussion.robot
plone/app/discussion/tests/robot/test_moderation.robot

This is part of https://github.com/plone/Products.CMFPlone/issues/3813
They are expected to fail for now, we need to figure out CI specially.
See plone/Products.CMFPlone#3813 for how to run them locally as CI is getting ready for it.

Playwright based robot test

---

news/188.bugfix.rst
plone/app/discussion/upgrades.py
setup.py

Do not depend on plone.api

---

.editorconfig
.flake8
.github/workflows/meta.yml
.gitignore
.meta.toml
.pre-commit-config.yaml
dependabot.yml
news/188.bugfix
plone/app/discussion/upgrades.py
pyproject.toml
setup.py
tox.ini

I removed use of `plone.api` in [2021](https://github.com/plone/plone.app.discussion/issues/188), but it crept up in a different place a year later.  So get rid of it again.
This needed a rerun with plone/meta, so some more changes ended up this PR.  The main change is in the first commit.

Remove plone api dependency from 4.x

---

news/182.bugfix
plone/app/discussion/browser/comments.pt
plone/app/discussion/browser/comments.py

Fix logic to obey `delete_own_comment_enabled` option
